export { default as Header } from './Header';
export { default as Footer } from './Footer';
export { default as Cards } from './Cards';
export { default as Carrousel } from './Carrousel';
export { default as Collaps } from './Collaps';
export { default as CollapsLocation } from './CollapsLocation';
export { default as InfoLocation } from './InfoLocation';
export { default as Star } from './Star';
export { default as Banner } from './Banner';